-- ==========================================================
-- КРОК 1: ОЧИЩЕННЯ (DROP)
-- ==========================================================
DROP TABLE work_logs CASCADE CONSTRAINTS;
DROP TABLE projects CASCADE CONSTRAINTS;
DROP TABLE customers CASCADE CONSTRAINTS;
DROP TABLE employees CASCADE CONSTRAINTS;
DROP TABLE qualifications CASCADE CONSTRAINTS;
DROP TABLE positions CASCADE CONSTRAINTS;

-- ==========================================================
-- КРОК 2: СТВОРЕННЯ ТАБЛИЦЬ (DDL)
-- ==========================================================

-- 2.1. Посади
CREATE TABLE positions (
    pos_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pos_name VARCHAR2(100) NOT NULL UNIQUE,
    bonus_coeff NUMBER(3,2) DEFAULT 1.0 CHECK (bonus_coeff >= 1.0)
);

-- 2.2. Кваліфікації
CREATE TABLE qualifications (
    qual_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qual_name VARCHAR2(100) NOT NULL UNIQUE,
    hourly_rate NUMBER(10,2) NOT NULL CHECK (hourly_rate > 0)
);

-- 2.3. Працівники (твої імена)
CREATE TABLE employees (
    emp_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(150) NOT NULL,
    pos_id NUMBER NOT NULL REFERENCES positions(pos_id),
    qual_id NUMBER NOT NULL REFERENCES qualifications(qual_id),
    manager_id NUMBER REFERENCES employees(emp_id)
);

-- 2.4. Замовники (твої дані)
CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR2(150) NOT NULL UNIQUE,
    has_debt NUMBER(1) DEFAULT 0 CHECK (has_debt IN (0, 1))
);

-- 2.5. Проекти (твої дані + вимоги ТЗ)
CREATE TABLE projects (
    project_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    customer_id NUMBER NOT NULL REFERENCES customers(customer_id),
    manager_id NUMBER NOT NULL REFERENCES employees(emp_id),
    complexity VARCHAR2(50) CHECK (complexity IN ('Low', 'Medium', 'High')),
    complexity_coeff NUMBER(3,2) DEFAULT 1.0,
    overhead_rate NUMBER(3,2) DEFAULT 1.40, -- Накладні витрати 40% за ТЗ
    start_date DATE DEFAULT SYSDATE
);

-- 2.6. Журнал робіт (з обмеженням 10 годин за ТЗ)
CREATE TABLE work_logs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id NUMBER NOT NULL REFERENCES employees(emp_id),
    project_id NUMBER NOT NULL REFERENCES projects(project_id),
    work_date DATE DEFAULT TRUNC(SYSDATE) NOT NULL, -- Додано дату для зарплати
    hours_worked NUMBER(4,2) CHECK (hours_worked > 0 AND hours_worked <= 10), -- ТЗ: max 10 годин
    description VARCHAR2(500)
);

-- ==========================================================
-- КРОК 3: НАПОВНЕННЯ ТВОЇМИ ДАНИМИ (DML)
-- ==========================================================

-- Посади та Кваліфікації
INSERT INTO positions (pos_name, bonus_coeff) VALUES ('Developer', 1.1);
INSERT INTO positions (pos_name, bonus_coeff) VALUES ('QA', 1.0);
INSERT INTO positions (pos_name, bonus_coeff) VALUES ('Team Lead', 1.25);

INSERT INTO qualifications (qual_name, hourly_rate) VALUES ('Junior', 20);
INSERT INTO qualifications (qual_name, hourly_rate) VALUES ('Middle', 35);
INSERT INTO qualifications (qual_name, hourly_rate) VALUES ('Senior', 50);

-- Працівники (твої імена)
-- Спочатку менеджер (Max Manager)
INSERT INTO employees (full_name, pos_id, qual_id, manager_id) VALUES ('Max Manager', 3, 3, NULL);
-- Тепер підлеглі (Alex Dev, Anna QA)
INSERT INTO employees (full_name, pos_id, qual_id, manager_id) VALUES ('Alex Dev', 1, 1, 1);
INSERT INTO employees (full_name, pos_id, qual_id, manager_id) VALUES ('Anna QA', 2, 2, 1);

-- Замовники (твої дані)
INSERT INTO customers (company_name, has_debt) VALUES ('Google', 0);
INSERT INTO customers (company_name, has_debt) VALUES ('Nova Poshta', 0);

-- Проекти (твої назви)
INSERT INTO projects (title, customer_id, manager_id, complexity, complexity_coeff)
VALUES ('AI Search', 1, 1, 'High', 1.5);
INSERT INTO projects (title, customer_id, manager_id, complexity, complexity_coeff)
VALUES ('Delivery App', 2, 1, 'Medium', 1.2);

-- Журнал робіт (твої записи)
INSERT INTO work_logs (emp_id, project_id, work_date, hours_worked, description)
VALUES (2, 1, CURRENT_DATE, 8, 'Coding backend');
INSERT INTO work_logs (emp_id, project_id, work_date, hours_worked, description)
VALUES (3, 2, CURRENT_DATE, 6, 'Testing app');

COMMIT;

-- Перевірка
SELECT * FROM work_logs;