-- =======================================================
-- БЛОК 1: СТВОРЕННЯ ТАБЛИЦІ АУДИТУ (Журнал історії)
-- =======================================================
-- Якщо база видасть помилку "name is already used by an existing object", 
-- значить таблиця вже є, просто переходь до Блоку 2.

CREATE TABLE audit_qualifications (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Автоматично генерує ID (1, 2, 3...)
    qual_name VARCHAR2(100),                                      -- Сюди запишемо назву посади
    old_rate NUMBER(10,2),                                        -- Сюди запишемо, яка ЗП була до зміни
    new_rate NUMBER(10,2),                                        -- Сюди запишемо нову ЗП
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP               -- База сама поставить точний час зміни
);

-- =======================================================
-- БЛОК 2: СТВОРЕННЯ ТРИГЕРА (Невидимий охоронець)
-- =======================================================
-- Виділи від слова CREATE до слова END; і натисни Ctrl + Enter
CREATE OR REPLACE TRIGGER trg_audit_rate_change
AFTER UPDATE OF hourly_rate ON qualifications
FOR EACH ROW
BEGIN
    -- Коли хтось міняє ЗП, тригер бере старі дані (:OLD) і нові (:NEW) 
    -- та тихенько вставляє їх у наш журнал audit_qualifications
    INSERT INTO audit_qualifications (qual_name, old_rate, new_rate)
    VALUES (:OLD.qual_name, :OLD.hourly_rate, :NEW.hourly_rate);
END;
/

-- =======================================================
-- БЛОК 3: ТЕСТУВАННЯ (Провокуємо тригер)
-- =======================================================
-- Виділи цей UPDATE і натисни Ctrl + Enter. (Змінюємо ЗП для Middle на 40$)
UPDATE qualifications 
SET hourly_rate = 40 
WHERE qual_name = 'Middle';

-- Обов'язково виділи COMMIT і натисни Ctrl + Enter, щоб зберегти зміну назавжди
COMMIT;

-- =======================================================
-- БЛОК 4: ПЕРЕВІРКА РЕЗУЛЬТАТУ
-- =======================================================
-- Виділи цей SELECT і натисни Ctrl + Enter. 
-- Якщо все вдалося, внизу з'явиться табличка з історією нашої махінації!
SELECT * FROM audit_qualifications;