-- =====================================================================
-- ЛАБОРАТОРНА РОБОТА №4: ТРИГЕРИ ТА АУДИТ ДАНИХ
-- База даних: TaskForge ERP (Варіант: Виконання проектів)
-- =====================================================================



    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- ОПИС: Створюємо таблицю, куди записуватиметься історія змін зарплат.
-- Якщо вона вже існує з минулих запусків - видаляємо її (DROP TABLE), 
-- щоб показати викладачу роботу з чистого аркуша. Помилку при DROP ігноруємо.
DROP TABLE audit_rate_history;

-- Створюємо структуру таблиці:
-- audit_id: автоматично генерує унікальні номери записів (1, 2, 3...)
-- old_rate / new_rate: зберігають фінансовий стан "ДО" і "ПІСЛЯ" зміни
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- change_date: база сама фіксує точний час операції (CURRENT_TIMESTAMP)
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
CREATE TABLE audit_rate_history (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qual_name VARCHAR2(100),
    old_rate NUMBER(10,2),
    new_rate NUMBER(10,2),
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- ОПИС: Створюємо DML-тригер (невидимого наглядача).
-- AFTER UPDATE OF hourly_rate: він прокидається ТІЛЬКИ тоді, коли хтось
-- :OLD та :NEW - системні змінні, які ловлять стару і нову суму.
-- змінює саме колонку hourly_rate (зарплату) в таблиці qualifications.
-- FOR EACH ROW: тригер спрацює окремо для кожного оновленого рядка.
-- :OLD та :NEW - системні змінні, які ловлять стару і нову суму.
CREATE OR REPLACE TRIGGER trg_rate_history_log
-- :OLD та :NEW - системні змінні, які ловлять стару і нову суму.
AFTER UPDATE OF hourly_rate ON qualifications
FOR EACH ROW
BEGIN
-- :OLD та :NEW - системні змінні, які ловлять стару і нову суму.
    -- Тригер самостійно копіює дані та робить запис у наш журнал аудиту
    INSERT INTO audit_rate_history (qual_name, old_rate, new_rate)
    VALUES (:OLD.qual_name, :OLD.hourly_rate, :NEW.hourly_rate);
END;
/


-- ОПИС: Тригеру потрібні реальні дані. Спочатку ми видаляємо ці посади 
-- (щоб уникнути помилки дублікатів ORA-00001), а потім створюємо їх заново 
-- з базовими ставками.
DELETE FROM qualifications WHERE qual_name IN ('Frontend Dev', 'Backend Dev', 'DevOps Eng', 'Data Sci');

-- Заселяємо посади (початкові суми)
INSERT INTO qualifications (qual_name, hourly_rate) VALUES ('Frontend Dev', 20.00);
INSERT INTO qualifications (qual_name, hourly_rate) VALUES ('Backend Dev', 25.00);
INSERT INTO qualifications (qual_name, hourly_rate) VALUES ('DevOps Eng', 35.00);
INSERT INTO qualifications (qual_name, hourly_rate) VALUES ('Data Sci', 40.00);

-- Зберігаємо цей початковий стан на жорсткий диск
COMMIT;

-- Виводимо табличку на екран (показуємо викладачу базові ставки)
SELECT * FROM qualifications;


-- ОПИС: Кульмінація захисту. Ми як менеджери просто оновлюємо ставки.
-- НЕВИДИМА МАГІЯ: Саме в цей момент фоново спрацьовує наш тригер із Кроку 2
-- і тихенько записує всю історію (старі і нові суми) в таблицю audit_rate_history.
UPDATE qualifications SET hourly_rate = 28 WHERE qual_name = 'Frontend Dev';
UPDATE qualifications SET hourly_rate = 32 WHERE qual_name = 'Backend Dev';
UPDATE qualifications SET hourly_rate = 45 WHERE qual_name = 'DevOps Eng';
UPDATE qualifications SET hourly_rate = 50 WHERE qual_name = 'Data Sci';

-- Затверджуємо фінансові операції
COMMIT;


-- ОПИС: Відкриваємо наш "сейф" аудиту. Викладач побачить тут 4 нових записи: 
-- хто, коли і на скільки змінив зарплату. Це доводить, що тригер працює ідеально.
SELECT * FROM audit_rate_history;